- src/pages/alcohols/search.js
- src/pages/community/[id].js
- src/pages/community/add.js
- src/pages/community/index.js
- src/pages/map/index.js
- src/pages/map/result.js
- src/pages/mypage/index.js
페이지 마다 상세 페이지, 검색 페이지 구성까지 완료했습니다 ~
> 폴더 구성 완료-> 마이페이지,지도페이지,게시판페이지

- package.json
- src/pages/_document.js
- src/pages/map/index.js
- yarn.lock
[feat] map 및 kakao map api 설정.
read.me 수정
> [feat] map 및 kakao map api 설정.

- src/features/map/MapBeginning.js
- src/pages/mapBegin/index.js
1.pages폴더에 mapBegin페이지 생성.
2.features폴더에 MapBeginning.js 컴포넌트 생성.
3.MapBeginning.js기본 UI구성 구축.
> [feat] 메인페이지2(기본상태) 생성

- src/features/AlcoholList.js
- src/hook/alcohol/useGetAllStore.js
- src/pages/alcohols/[id].js
- src/styles/globals.css
술집 리스트 전체조회 하기
1. 전체조회하기 가능
2. api와 같이 page, size 쿼리스트링으로 끊어서 조회도 가능하게 되어있음
> [feat]술집리스트 전체조회하기 완료

- src/features/map/MapBeginning.js
1. 지도 기본 세팅
2. 버튼 클릭시 지도 중간지점 찾기 URL로 이동 구현(React-Query로 구현)
MapBeginning.js 파일의 기능 구현은 완료. 
->요소들 대략적인 위치만 잡혀있기에 CSS작업 추후 필요.
> [feat] MapBeginning.js 파일 기능 구현 완료.

- src/pages/map/index.js
기본 UI수정
1. 지도 크기 조절
2. "추가"버튼 추가
3. 설명 글귀 추가
4. Input 박스 기본 하나로 변경.
UI 변경으로 UI다시 수정. 
->
1. CSS 필요
2. "추가" 버튼 기능 
3. 인풋 창 클릭 시 키워드 검색 모달창 기능 구현 
4. 모달창 키워드 state 받아오기.
> [style] map 페이지 index.js 파일 수정.

- src/features/map/AddingInputBoxButton.js
- src/pages/map/index.js
features폴더에 AddingInputBoxButton.js 파일 생성 후 기능 구현. 
map페이지 index.js파일에서 임포트하여 사용.
추가버튼클릭시 검색인풋박스 4개까지 생성 기능 완료.
->CSS 보완 필요.
해당 인풋박스 클릭시 키워드 검색 모달창 연결 필요.
> [feat] AddingInputBoxButton 기능 구현.

- src/components/Modals/SearchKeywordModal.jsx
- src/features/map/AddingInputBoxButton.js
- yarn.lock
Features폴더에 SearchKeywordModal.jsx 파일 생성 &
AddingInputBox.js파일에 모달창 포털 구현 완료.
AddingInputBox.js파일에서 Input박스 클릭 시 모달창 넘어가도록 포털구축.
인풋 박스 클릭 시 Modal 창 실행 및 닫기 버튼 구현도 완료.
인풋박스 readOnly로 설정.
->
1. 기본 CSS만 완료하여 CSS 필요.
2. 모달 창에서 키워드 검색 로직 구축 필요
3. 모달 창에서 키워드 검색 후 선택하면, x,y값 state로 저장되어 AddingInputBox.js파일로 갈 수 있도록 로직 필요.
> [feat] map페이지 모달창(키워드검색위한) 기본 기능 구현.

- src/components/Modals/SearchKeywordModal.jsx
SearchKeywordModal.jsx에서 검색모달창 기본 UI구축 및 기본 Style.
1. 카카오 map  
2. 키워드 검색 input box 
3. 검색 버튼(임시) 
4. 확인 버튼(모달창 닫기)
5. h1태그
6. 검색 값 담을 div
기본 모달 창UI는 완성
-> 
1. 키워드 검색 로직 및 맵마커 
2. 검색버튼handler
3. 검색 값 데이터 받아 div 보여지기  구축필요
> [feat][style]

- src/components/Modals/SignInModal.jsx
**로그인 모달 css 수정 및 정리** close#82
수정 된 디자인에 따라 로그인 창을 수정하였습니다. 
모드를 두개를 줘
로그인 모달창 내에서 바로 비밀번호 찾기 모달을 띄워주는 방식으로 코드를 짯습니다.
> 로그인 모달 css 수정 및 정리

- src/components/Modals/SignInModal.jsx
페이지로 구성 되어있던 비밀번호 찾기 기능을 
로그인 모달창 내로 구성시켰습니다.
> 84 fix find password

- src/components/Modals/SearchKeywordModal.jsx
- src/features/map/AddingInputBoxButton.js
- src/features/map/MapBeginning.js
1. SearchKeywordModal.jsx에 키워드 검색 로직 구현 코드 및 랜딩 코드 완료. 
-> 랜딩페이지 및 로직 컴포넌트 따로 만드려 하였지만 오류 해결 못하여 한 페이지에 우선 구성. 추후 리팩토링 필요.
-> 키워드검색로직에 포함된 것들.
1) 키워드 검색 및 지도에 마커찍기
2)  여러개 마커 찍기
3)  pagination 구현 
4) 재 검색시 마커 지워지며 검색
5) 검색 값 받기
2. AddingInputBoxButton.js파일 버그로 수정(import 스펠링 오타 수정) 
3. MapBeginning.js파일 버그 수정(대소문자 오타 오류 수정)
=>SearchKeywordModal.jsx에 검색 받아온 값 받아 보여지도록 코드 구성 필요 및 CSS 필요.
> [feat][fix] 모달창 키워드 검색 로직 구현 및 버그 수정

- src/components/Modals/SignUpModal.jsx
**회원 가입 모달 CSS 수정**  close#88
X아이콘 모달창에 달아주고 
인풋 클릭하면 뜨던 빨간 조건식 말해주는 태그 빼고 
중요한 인풋 에 타이틀 옆에 옅은 회색으로 주의사항 기입하였습니다
> 회원가입 css 수정

- src/components/Modals/SearchKeywordModal.jsx
SearchKeywordModal.jsx파일 검색하여 받는 부분 뷰 화면 구성 및 간단한 CSS.
수정해야 할 점
=> 
1. 검색차 2번 클릭해야 검색되는 버그.
2. 검색결과 디자인대로 목록 및 CSS 수정.
3.  전체적인 CSS
4. 검색 결과 클릭하여 선택할 수 있도록 기능 수정.
5. 선택 state값 내려줄 수 있도록 기능 추가.
> [feat][style] 키워드검색 모달창 뷰화면 구성 및 기본 CSS

- src/components/Atoms/Button.jsx
- src/components/Molecules/LinkToNav.jsx
- src/features/mypage/Log.js
- src/shared/axios.js
- src/shared/instance.js
- src/styles/globals.css
**Link To Nav 파일 수정** 
디자인 변동으로 인해 네비게이션 바 수정했습니다 .
토큰 유무를 통해 
리스트  탐색  커뮤니티  는 기본적으로 두고     없을 때 로그인과 회원가입이 보이고   있을 때(로그인 시) 로그아웃과 {이름}님
으로 나오도록 변경했습니다.
이름 부분을 누르면 밑으로 메뉴 탭이 나오고 이메일과 , 마이페이지와 로그아웃 버튼이 나오도록 했습니다.
> 네비게이션 바 수정 완료

- src/components/Modals/SearchKeywordModal.jsx
- src/features/map/AddingInputBoxButton.js
- src/pages/signup.js
SearchKeywordModa.jsx에서 검색값 중 리스트 클릭 시,
장소 선택되며 지도 움직이고 리스트에 초록색 선 및 V 표시생김.
AddingInputBoxButton.js에 props로 해당 장소 value 넘겨주기는 현재 진행중.
지도 및 검색리스트 크기 조절
=> 현재 props로 값 내려주는 거 에러 해결 중. 중간 Merge 진행.
> [feat][style]키워드검색 value 저장 및 리스트 클릭 시 CSS 수정.

- src/shared/instance.js
> instance 에러 수정

- src/components/Molecules/LinkToNav.jsx
네비 바에 div 사용으로 오류 뜨던 부분 
<> 으로 영역 잡아주고 잔 css 처리 완료 했습니다.
> 네비 바 오류 해결

- src/pages/_document.js
환경변수 수정(백엔드https서버배포) 및 환경변수 카카오지도 app key 오타 수정
> [fix]서버 배포위한 환경변수 수정

- src/components/Modals/SettingModal.jsx
- src/features/mypage/Save.js
비밀번호 변경시 기존 비밀번호도 입력하도록 수정하였습니다.
> 125 feat change password

- src/components/Molecules/LinkToNav.jsx
> 133 fixnav

- src/components/Atoms/Button.jsx
- src/features/mypage/FindPost.js
> 날라간 코드 업로드

- src/features/map/AddingInputBoxButton.js
자식컴포넌트인 SearchKeywordModa.jsx에서 키워드 검색 및 리스트 클릭된 장소 값을 부모 컴포넌트인 AddingInputBoxButton.js의 props로 올려줌. 이 값을 꺼내어 활용해 input박스에 장소이름을 나타내어 주었다.
=> 한가지 문제점은 각각의 인풋박스에 각각 선택된 값이 들어가는 게 아니라 하나의 장소 선택하면 4개 인풋 모두 같은 값이 들어감.
> [feat]모달창 props 값을 부모컴포넌트에서 꺼내어 input의 value 활용

- src/features/map/AddingInputBoxButton.js
각각 인풋박스에 모달창에서 검색한 각각의 값이 들어가지 않고 모두 같은 값이 들어감. 
현재 인풋 박스는 버튼을 누르면 하나씩 추가되는 방식으로 만들어짐. 4개까지. 그래서 그에 맞게 value값(장소이름) 넣도록 로직 구현.
> [fix] 각각의 인풋에 각각의 value값 지정

- src/features/map/AddingInputBoxButton.js
모달창에서 키워드검색 후 리스트 장소 클릭 하여 보낸 props값을 백서버 request 폼으로 가공 로직 구현완료
{
x1: '',
y1: '',
x2: '',
y2: '',
x3: '',
y3: '',
x4: '',
y4: '',
}
폼으로 checkedPlace state값을 가공.
=>
이 값을 가지고 서버와 통신 로직 구현하기
> [feat] 모달창props값 백서버 request 폼으로 가공 로직

- src/features/map/AddingInputBoxButton.js
props로 받은 가공된 데이터 react-query와 axios 활용하여 서버 통신 성공.
현재 페이로드 약속한 api request form(x,y,x2,y2~x4,y4)로 잘 들어감. 그렇지만 Cors 오류로 중간지점은 못 받음.
현재 백엔드 서버 https로 옮겨 local환경에서 통신 불안정. 403에러도 같이 받음.
우선 머지 및 배포 후, 배포 환경에서 확인 예정
=> 현재 지도에 각각의 출발지 마커찍고 중간지점 받으면 중간 지점 마커 찍는 로직 구현 필요
> [feat]props로 받은 가동된 데이터로 서버통신 로직 구현

- src/features/map/AddingInputBoxButton.js
- src/pages/map/index.js
1. props가져온 각각의 값들로 지도에 마커찍기(출발지 마커)
2. 그와 동시에 해당 마커위치로 지도 이동
3. map페이지 index.js파일 return값 수정(몇가지 UI및 중간 값 구하기 버튼 AddingInputBoxButton.js파일로 옮김)
=>
1. 후에 AddingInputBoxButton.js파일 리팩토링 필요.
2. 모달창 닫기 누르면 각각의 값 input박스에 잘 들어가고 마커도 잘 찍히지만 장소 수정했을 때 해당 마커 지워지지 않음. 이 부분 수정 필요.
3. 불필요한 코드들 정리 필요
4. CSS필요
5. 모달창에서 검색시 버튼 2번눌러야 검색되는 버그 수정 필요.
> [feat][fix]props가져온 값들로 지도에 마커찍기

- src/features/map/AddingInputBoxButton.js
지도 중간값 받아오기 통신 에러 해결 코드 수정.
(request값에 {} 빼서 그대로 보줌)
> [fix]지도 중간값 받아오기 통신 에러 해결 코드 수정.

- src/components/Modals/SignInModal.jsx
- src/components/Molecules/LinkToNav.jsx
닉네임 로컬 스토리지와 쿠키에 저장 , 로그아웃 버튼 누르면 전부 삭제 되도록 구현 완료
쿠키와 로컬스토리지에 저장
const { mutate: register, status } = useMutation({
mutationFn: async (user) => {
const data = await apis.post('/users/login', user);
//디코드 활용
const decoded = jwtDecode(data.headers.access_token);
console.log('decoded', decoded);
console.log('로그인data', data.data.data);
alert(`${decoded.sub}로그인 성공 했습니다❤️`);
cookies.set('access_token', data.headers.access_token, { path: '/' });
cookies.set('refresh_token', data.headers.refresh_token, { path: '/' });
cookies.set('nick_name', data.data.data, { path: '/' });
localStorage.setItem('nick_name', data.data.data, { path: '/' });
},
삭제버튼에도 추가 완료
const deleteTokens = () => {
cookies.remove('access_token');
cookies.remove('refresh_token');
cookies.remove('nick_name'); …
> 닉네임 로컬스토리지와 쿠키에 저장 , 로그아웃 버튼 누르면 전부 삭제 되도록 구현 완료

- src/features/CommentsList.js
자신의 댓글에만 삭제 수정 버튼이 뜨도록 기능 구현 하였습니다. 
로그인 때 저장한 닉네임 값과 불러온 데이터를 비교해서 같을 때만 뜨도록 하였습니다
> 자신의 댓글에만 변형이 가능하도록 구현 완료

- src/features/map/AddingInputBoxButton.js
중간 위치 받기위한 서버 Request주는 위도경도값(x,y값) 뒤바뀐거 코드 수정.
> [fix]서버Request주는 위도경도값 뒤바뀐거 코드 수정.

- src/features/map/AddingInputBoxButton.js
> [fix]서버Request주는 위도경도값 뒤바뀐거 코드 수정2

- src/features/map/AddingInputBoxButton.js
전달 받은 값 장소 마커 여러개 찍기 실패.
장소 찍힐 때, 해당 장소로 지도 이동 기능까지는 구현.
> [fix]전달 받은 값 장소 마커 여러개 찍기 실패.

- src/components/Modals/SearchKeywordModal.jsx
SearchKeywordModal.jsx파일 style
=> CSS 디테일 필요 및 수정 필요
> [style]SearchKeywordModal.jsx파일 style

- src/features/map/AddingInputBoxButton.js
중간지점 마커 찍은 후 지도이동 기능 구현(AddingInputBoxButton.js)
(첫번째 시도. 로컬환경 https 배포 후 서버연결 에러로 배포환경에서 중간지점 관련된 기능 확인 가능으로 몇번의 머지 될 수도)
> [feat]중간지점 마커 찍은 후 지도이동 기능 구현

- src/features/map/AddingInputBoxButton.js
중간지점 마커 후 지도이동 기능(AddingInputBoxButton.js)
시도2
> [feat]중간지점 마커 후 지도이동 기능(AddingInputBoxButton.js)

- src/features/map/AddingInputBoxButton.js
중간지점 마커 후 지도 이동(AddingInputBoxButton.js)
3번째시도
> [feat] 중간지점 마커 후 지도 이동(AddingInputBoxButton.js)

- src/features/map/AddingInputBoxButton.js
[feat]중간지점 마커 후 지도 이동 기능 구현 성공
성공.
중간지점 좌표 response 받은 후 useEffect로 지도 해당 좌표로 이동.
> [feat]중간지점 마커 후 지도 이동 기능 구현 성공

- src/features/map/AddingInputBoxButton.js
AddingInputBoxButton.js의 헤더에 토큰 제거.
지도 탐색 시 토큰 필요없음 => 제거 완료
> [fix]AddingInputBoxButton.js의 헤더에 토큰 제거

- src/features/map/MapMidPoint.js
kakaoApi (중간 위치 검색 값 DB저장 및 불러오기) 서버통신
=>react-query 중 ueQuery 사용하여 서버와 통신 성공. 
response 값 정상적으로 들어옴.
> [feat] kakaoApi (중간 위치 검색 값 DB저장 및 불러오기) 서버통신

- src/pages/oauth.js
인가 코드 받아 온 것을
{code : code} 해서 json 형식으로 api post 요청 보내는 것 까지 구현 완료 했습니다 .
> 카카오 소셜 로그인 인가 api로 보내기

- src/features/kakaoLogin/KakaoLogIn.js
> 리다이렉트 url 변경

- src/features/kakaoLogin/KakaoButton.js
- src/features/kakaoLogin/KakaoLogIn.js
- src/pages/OAuth/Kakao.js
- src/pages/OAuth/index.js
- src/pages/oauth.js
리다이렉트 url 오류가 서버와 함께 계속 되고 있어서 계속 수정중입니다.
> 카카오 로그인 오류 수정중

- src/components/Modals/SignInModal.jsx
- src/features/kakaoLogin/KakaoButton.js
- src/features/kakaoLogin/KakaoLogIn.js
- src/pages/OAuth/Kakao.js
- src/pages/oauth.js
> 227 fix kakao login

- src/features/mypage/Calender.js
- src/features/mypage/EventForm.js
- src/features/mypage/Log.js
리액트 캘린더에 
api get 요청으로 캘린더에 표시하고 옆에 로그할 준비 끝냈습니다. 
api post 요청으로 서버에 보내줄 형태 만들어놨습니다 .
> 캘린더 get 이랑 post 준비 완료

- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapMidPoint.js
MapMidPoint.js, SearchKeywordModalPortal.jsx 파일 코드 정리 및 설명주석
(contextAPI로 prop값 전달하던, Props로 값 전달하려던 흔적들 지우고 코드들 정리)
추가한 코드에 설명 주석으로 작성.
코드 순서 조금 조정(MapMidPoint.js)-> 값 받고 그 값으로 서버와 get통신 하는 거로.
> [fix]MapMidPoint.js, SearchKeywordModalPortal.jsx 파일

- src/features/map/MapMidPoint.js
- src/pages/_document.js
지도 생성 및 중간위치좌표 props받은 값으로 지도 마커찍기.
=> 해당 마커 찍은 주변 술집들 마커찍고 리스트 보여줘야함. kakaoAPI DB저장 후 받아온 값으로 지도에 나타내야한다.
> [feat]지도 생성 및 중간위치좌표 props받은 값으로 지도 마커찍기.

- src/components/Modals/SearchKeywordModal.jsx
- src/features/map/MapMidPoint.js
지도생성(방법수정) 및 중간지점 주변 술집 마커 및 리스트 나타내기 구현.
해결되어야할 것들
=> 
1. 중간위치 마커 따로 찍기
2. 페이지 실행되자 마자 모든 동작 다 되도록 하기(현재 useEffect로 지도 불러오지만 모달창과 같이 keywordSearchSubmitHandler로 2번 이상 실행해야지 마커까지 찍힘. 버그 수정 필요)
3. Pagination 에러 해결 및 기능 구현
4. 리스트에서 장소 선택하고 값 저장하기
> [feat] 지도생성 및 중간지점 주변 술집 마커 및 리스트 나타내기 구현.

- src/components/Modals/Pagenation2.js
- src/components/Modals/chunk.js
- src/features/mypage/Calender.js
- src/features/mypage/Log.js
캘린더 조회 및 입력 기능 구현 
조회 시 페이지네이션 가능하게 기능 구현
> 캘린더 입력 및 조회 , 페이지네이션

- src/components/Atoms/Button.jsx
- src/components/Templates/mainpage/MainFirstSection.jsx
- src/features/AlcoholList.js
- src/features/post/CommunityList.jsx
- src/features/post/Post.jsx
- src/hook/alcohol/useGetAllStore.js
- src/hook/post/useDeletePost.jsx
- src/pages/_app.js
- src/pages/_document.js
- src/pages/alcohols/[id].js
- src/pages/community/[id].js
- src/pages/community/add.js
- src/styles/globals.css
> [feat] 검색기능

- src/features/mypage/Log.js
- src/pages/mypage/index.js
캘린더 모듈의 css를 변경하고
남긴 기록의 데이터 수정을 할 때 
input 3개로 뒀던 입력창을 
input type text ,  input type date , textarea 로 각기 기능에 맡게 다양하게 구성하였습니다. 
close #265
> 264 style calender

- src/components/Modals/SearchKeywordModalPortal.jsx
*X 버튼 핸들러 ( 입력된 값 inputValue 초기화. x 버튼 누를시 가장 아래의 값 부터 차례로 삭제되는 버그 발견 => 해당 인풋박스의 X 버튼 누를시 해당 인풋박스의 값 삭제 [index]속성 주어 버그 해결 )
=>mapMarker는 지워지지 않음. 버그 수정 필요
> [feat]onInputClearHandler

- src/components/Atoms/Flex.jsx
- src/components/Modals/SearchKeywordModalPortal.jsx
- src/components/Themes/theme.js
참고부탁드립니다. 
@@
theme.js파일 hover, active color추가, 
Flex.jsx 파일 FlexColumnCenter 추가@@
*Map탐색페이지 버튼 스타일 및 위치 수정
*Map탐색페이지 중간술집버튼 hover color , active color수정
*Map탐색페이지 중간위치찾기 버튼 수정(출발지2개입력 후 버튼 생김 -> 맨 처음부터 비활성화버튼으로 보여지도록) 
*Map탐색페이지 버튼 스타일 및 위치 수정
*Map탐색페이지 color theme.js로 리팩토링
*Map탐색페이지 font 리팩토링
*Map탐색페이지 그 외 flex,wrapper등 리팩토링
> [style][refactor]searchKeywordModalPortal.jsx파일 CSS

- src/components/Modals/SignInModal.jsx
토스트메시지 핸들러를 지운다는 것을 로그인 핸들러를 삭제해서 일어난 오류였고 해결 완료했습니다.
> 핸들러 모르고 다른 것 지움

- src/components/Modals/SearchKeywordModal.jsx
- src/features/map/MapBeginning.js
- src/features/map/MapMidPoint.js
SearchKeywordModal.jsx, MapMidPoint.js, MapBeginning.js 파일 CSS
및 MapMidPoint.js 카테고리별 술집 검색 로직 및 버튼 CSS
=>카테고리별 지도에 마커 및 리스트 잘 나오지만 버튼을 3번 눌러야 나오는 버그 해결해야함.
=>뒤로가기 버튼 기능 및 css 하기
> [style][feat]SearchKeywordModal.jsx,

- src/features/map/MapMidPoint.js
카테고리 버튼 여러번 클릭해야 값 나오는 부분 수정. (서비스 테스트 앞두고 있어 우선 UseEffect로 해결)
술집(종합)은 1번이면 되지만 다른 버튼은 2번 클릭해야 나오는 점, 더 수정 필요
> [fix] 카테고리 버튼 여러번 클릭해야 값 나오는 부분 수정.

- src/components/Modals/SearchKeywordModal.jsx
- src/components/Modals/SearchKeywordModalPortal.jsx
SearchKeywordModal.jsx 파일 CSS(닫기버튼추가) 및 검색어 미 입력시 보더색 및 포커싱 변화.
SearchKeywordModalPortal.jsx의 마커 크기 변경
> [style][fix] SearchKeywordModal.jsx 파일

- src/components/Modals/SearchKeywordModal.jsx
- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapMidPoint.js
SearchKeywordModalPortal.jsx에서 출발지 값 MapMidPoint로 전달하기.CSS도 완성
해당 출발지 값에 빈값이면 그 값 빼고 값 들어있는 갯수만큼 인풋 창 다음 페이지 만들어지고 값 들어감. 그리고 그 인풋창 앞에 A~D까지 인풋 숫자에 값 붙여서 자동적으로 배치.
> [feat][style]SearchKeywordModalPortal.jsx에서 출발지 값

- src/features/map/MapMidPoint.js
MapMidPoint.js파일 기능추가
장소 리스트 더블클릭 시 해당 장소 게시판으로 이동(새 창 열어서 이동).
div태그 추가하여 설명글 추가
> [feat][style]MapMidPoint.js파일 기능추가

- src/components/Modals/SearchKeywordModalPortal.jsx
중간위치찾기 버튼 클릭시 버그 해결.
중간 위치 찾기 버튼 클릭 시,
1. 입력된 인풋창 주소 변경 불가하도록 설정
2. X버튼(취소버튼)비활성화 및 연하게 되도록 표현
3. 친구추가 버튼 비활성화 함
> [fix]중간위치찾기 버튼 클릭시 버그 해결.

- package.json
- src/components/Modals/SignInModal.jsx
- src/features/kakaoLogin/KakaoLogIn.js
- src/features/map/MapAppointment.js
- src/features/map/MapBeginning.js
- src/features/mypage/GetMyAlcohols.js
- src/features/mypage/GetmyPost.js
- src/features/mypage/MyWritePost.js
- src/hook/alcohol/useGetStore.js
- src/pages/mapmidpoint/index.js
- src/pages/test/index.js
- yarn.lock
> 맵어포인트먼트 로그인 전 후 페이지 만들기

- src/features/map/MapAppointment.js
약속잡기 버튼을 누르면 
moment로 잡힌 날짜의 값을 2023-05-01 형태로 들어오게 조정했습니다.
> 약속잡기에 날짜 값 들어가게 조정

- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapMidPoint.js
[feat][style]중간위치술집 검색 카테고리 추가(오뎅바는 주석처리) 및 카테고리 스크롤 처리
> [feat][style]중간위치술집 검색 카테고리 추가(오뎅바는 주석처리).

- src/components/Molecules/LinkToNav.jsx
> 설문조사 링크 추가

- src/components/Modals/SearchKeywordModal.jsx
- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapAppointment.js
- src/features/map/MapMidPoint.js
- src/pages/mapmidpoint/index.js
SearchKeywordModal.jsx 파일 지도 및 리스트 height부분 수정
SearchKeywordModalPortal.jsx 파일 코드정리
MapAppointment.js 파일 수정(props)
MapMidPoint.js 파일 수정(props)
index.js(mapmidpoint)파일에 MapAppointment 주석처리(미완성)
> [fix]배포 전 수정

- src/components/Modals/SignInModal.jsx
- src/components/Modals/SignUpModal.jsx
- src/components/Modals/SignUpPortalExample.jsx
- src/components/Molecules/LinkToNav.jsx
1. 로그인 시 모달창에 회원가입 버튼 누르면 바로 회원가입 모달창 뜨게하기 
2. 회원가입 비밀번호 타당성? 맞으면 바로 입력창에 초록 브이 띄워주기 
3. 비밀번호 확인도 마찬가지로
4. 입력값이 타당하지 않으면 회원가입 시 다음으로 넘어가지 않도록 했습니다.
> 342- 로그인 회원가입 수정사항 조정

- src/components/Modals/SearchKeywordModalPortal.jsx
SearchKeywordModalPortal.jsx파일 지도 출발지 마커 버그 해결
출발지 바꿔도 해당 인풋박스 주소에 맞게끔 마커 지워지고 생김. 
인풋값 지우면 마커도 지워짐.
그 안의 값도 잘 바뀌어 중간위치도 잘 찍히는 부분 테스트 확인.
> [fix]SearchKeywordModalPortal.jsx 지도 출발지 마커 버그 해결

- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapAppointment.js
- src/features/map/MapMidPoint.js
MapMidPoint.js에서 장소데이터 Props보내줌.
MapAppointment.js에서 props받아 장소 나타내줌. 
MapAppointment 페이지 CSS 완성. 조금의 수정 필요. 
MapMidPoint.js에 스크롤내려주는 버튼 임의로 만듬.
console다 지움.
> [feat][style] MapMidPoint.js에서 장소데이터 Props보내줌.

- src/components/Modals/SearchKeywordModal.jsx
- src/components/Modals/SearchKeywordModalPortal.jsx
- src/components/Templates/mainpage/MainLastSectionMovie.jsx
- src/components/Templates/mainpage/MainSecondSection.jsx
- src/features/map/MapAppointment.js
- src/features/map/MapBeginning.js
- src/features/map/MapMidPoint.js
지도 및 전체적인 포지션, 비율 등 조절.
13인치 모니터 및 32인치 모니터에서 확인
조금 더 수정필요.
> [style] 지도 및 전체적인 포지션, 비율 등 조절.

- src/components/Modals/SearchKeywordModalPortal.jsx
중간위치 찾기 후에도 출발지 변경 가능하도록 수정.
useEffect로 장소 변경시 중간위치찾기 버튼 다시 활성화 및 중간술집검색 비활성화
중간위치값(midPoint) 찾았어도 인원추가 및 장소 삭제 버튼 활성화.
> [fix][style]중간위치 찾기 후에도 출발지 변경 가능하도록 수정.

- src/components/Modals/SearchKeywordModal.jsx
- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapAppointment.js
- src/features/map/MapMidPoint.js
SearchKeywordModal.jsx에서 지도 및 리스트 warp에 max-width,height 줌. 
SearchKeywordModalPortal.jsx에서 값 취소시에도 인풋박스 disabled되어 해당 버그 수정. 
MapMidPoint.js에 전반적 CSS. 특히 카테고리 가로 스크롤 구현 및 CSS.
MapAppointment.js에 전체wrapper에 margin-top 속성 주어 페이지 조금 갭줌.
> [style][fix] 디테일 CSS

- src/components/Modals/SignInModal.jsx
- src/components/Modals/SignUpModal.jsx
- src/features/mypage/Log.js
- src/hook/useConfirm.js
-회원가입시 ㅇ이메일 인증 절차 추가
-로그인 모달창에 커서 포인터 뜨도록 설정
> 회원가입 이메일 인증추가

- src/features/map/MapMidPoint.js
중간지점 에러시 새로고침해도 계속 에러나는 부분 기능추가
=> midPoint값이 없어지면 새로고침되며 map 페이지로 이동되도록 useEffect.
> [feat]중간지점 에러시 새로고침해도 계속 에러나는 부분 기능추가

- src/components/Atoms/Button.jsx
- src/components/Atoms/TrashButton.jsx
- src/features/mypage/EventForm.js
- src/features/mypage/Log.js
- src/features/mypage/LogMeet.js
- src/features/mypage/LogMyDay.js
로그 파일에 
약속만들기와 캘린더 기록 부분 두개의 탭을 만들어줘야 해서 
Log 에서 LogMeet  , LogMyDay 두 파일로 나눠줬습니다. 
LogMeet은 약속을 만들고 나면 지도와 날짜 술집 정보가 오는 것이고 
LogMyDay는 내가 적고 싶은 날짜를 클릭해서 간단히 원하는 것을 기록하는 것입니다. 
Log 파일에 캘린더를 공통으로 두고 
각각 분기해서 만들어진 일정의 날짜를 다른 dot로 표시해주었습니다.
> 약속만들기 조회 (지도빼고 완료)

- src/pages/test/index.js
build 배포 에러 해결(/test에서 MapAppointment 임포트삭제)
TypeError: Cannot destructure property 'address_name' of 'checkedPlace' as it is undefined.
--
03:06:14.858 | at MapAppointment (/vercel/path0/.next/server/chunks/314.js:199:5)
03:06:14.860 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
03:06:14.860 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
03:06:14.860 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
03:06:14.860 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
03:06:14.860 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404) …
> [fix] build 배포 에러 해결(/test에서 MapAppointment 임포트삭제)

- src/components/Modals/SearchKeywordModal.jsx
모달창 바깥쪽 눌렀을때 모달 닫히도록
=> Modal이랑 Overlay랑 따로 줘서 동등관계주고 바깥쪽에 onClick={onClose}
> [feat]모달창 바깥쪽 눌렀을때 모달 닫히는 기능

- src/components/Modals/Pagenation2.js
- src/components/Modals/SettingModal.jsx
- src/components/Modals/SignUpModal.jsx
- src/components/Molecules/LinkToNav.jsx
- src/features/mypage/LogMeet.js
- src/features/mypage/LogMyDay.js
close #397 
1. 페이지네이션 글자 간격조정
2. class -> className 으로 수정해서 Dom 오류 해결
3. 설문조사 링크 삭제
4. 로그 페이지에 조회 최신 입력순으로 배순서 변경
> 397 fixsomeerror

- src/components/Modals/SearchKeywordModal.jsx
SearchKeywordModal.jsx : 장소 리스트 CSS 및 클릭시 디자인 (리스트장소 선택시 V표시 예쁜거로), X버튼 위치 조정
> [style]SearchKeywordModal.jsx : 장소 리스트 CSS 및 클릭시 디자인

- src/features/map/MapAppointment.js
MapAppointmet.js파일 Syntax Error해결.
> [fix]MapAppointmet.js파일 Syntax Error해결.

- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapMidPoint.js
SearchKeywordModalPortal.jsx : 중간 위치 찾기 최대 4인 미리 알 수 있도록 설명 글 추가.
SearchKeywordModalPortal.jsx :  중간위치 찾았을 때 alert창 메세지변경.
MapMidPoint.js 띄어쓰기 안 되있는 것처럼 보이는 부분 letter-spacing: 1px;
> [style]SearchKeywordModalPortal.jsx, MapMidPoint.js CSS

- src/features/map/MapAppointment.js
배포오류해결(MapAppointment.js syntax error)
어제 오후부터 2번 고쳤던 문제로 팀원 머지시 풀 당기고 머지 부탁드립니다.
> [fix]배포오류해결(MapAppointment.js syntax error)

- src/components/Modals/SearchKeywordModal.jsx
- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapMidPoint.js
[style]map관련 페이지 위치 및 높이,넓이 수정(vh,vw -> %,px로 변경(가장 밖 감싸는 부분 제외))
> [style]map관련 페이지 위치 및 높이,넓이 수정

- src/pages/alcohols/[id].js
[fix]alcohols 페이지 [id].js 지도 부분 로딩 오류로 수정
=> 지도 불러오는 방법 변경. useEffect로 지도 바로 실행시켜줌.
> [fix]alcohols 페이지 [id].js 지도 부분 로딩 오류로 수정

- src/components/Molecules/LinkToNav.jsx
- src/features/AddComment.js
- src/features/AddReComment.js
- src/pages/alcohols/[id].js
로그인 이전에 댓글기능과 게시물 작성 불가하도록 설정했습니다 .
토큰 에러 라는 얼럿 대신 로그인 후 이용부탁하는 어럿으로 바꾸었습니다.
> 디테일 사항 반영 수정

- src/features/map/MapAppointment.js
- src/features/map/MapMidPoint.js
MapMidPoint.js파일, MapAppointment.js파일 스타일 수정출발지 위치 및 약속잡으러가기 버튼 위치 수정. 약속만들기페이지 margin bottom 수정
> [fix][style] MapMidPoint.js파일, MapAppointment.js파일 스타일 수정

- src/components/Modals/SearchKeywordModal.jsx
- src/components/Modals/SearchKeywordModalPortal.jsx
- src/features/map/MapAppointment.js
- src/features/map/MapBeginning.js
- src/features/map/MapMidPoint.js
MapMidPoint 코드 리팩토링 및 지도 관련 파일 코드정리
아래 코드 중복되는 부분 굉장히 많음. 코드 효율적으로 작성하기 위하여 및 유지보수, 성능개선 위해서 해당 부분 수정하였지만, 수정 코드정상 동작 X.
[원래 코드]
`//  칵테일바 마커 및 리스트 불러오기
const [cocktailPage, setCocktailPage] = useState(null);
async function getCocktailPage() {
const response = await apis.get(`/kakaoApi?y=${midPointProp?.lat}&x=%20${midPointProp?.lng}&query=칵테일바&radius=1500&page=1&size=15&sort=distance`, midPointProp);
setCocktailPage(response?.data);
}
//  칵테일바 submit button Handler
const getCocktailPageSubmitHandler = async (e) => {
e.preventDefault();
const cocktailPage = await getCocktailPage();
if (cocktailPage) {
GetSpotsNearbyMidPoint(cocktailPage?.documents);
}
GetSpotsNearbyMidPoint(kakaoApiCocktail)
};
const kakaoApiCocktail = cocktailPage?.documents
//  일본식주점 마커 및 리스트 불러오기
const [izakayaPage, …
> [fix][refactor]MapMidPoint 코드 리팩토링 및 지도 관련 파일 코드정리

- README.md
[docs]READEME.md 수정
프로젝트 설명으로 변경
> [docs]READEME.md 수정

- src/features/map/MapAppointment.js
- src/features/map/MapMidPoint.js
- src/pages/index.js
[style] MapMidPoint.js 및 메인페이지 CSS 수정, MapAppointment.js수정
> [style] MapMidPoint.js 및 메인페이지 CSS 수정,
